### ISSUE TITLE
Not able to create user using command "python users.py -c"

### ISSUE THREAD

**Issue by thirumalx** [aws-samples/chalice-workshop#39]
Getting the following error for the command "python users.py -c"

```
(venv38) Thirumals-Air-2:vfc-lambda thirumal$ python users.py -c
Username: thirumal
Password: 
Traceback (most recent call last):
  File "users.py", line 85, in <module>
    main()
  File "users.py", line 77, in main
    create_user(args.stage)
  File "users.py", line 25, in create_user
    password_fields = encode_password(password)
  File "users.py", line 40, in encode_password
    hashed = hashlib.pbkdf2_hmac('sha256', password, salt, rounds)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by brewsfab** [comment]
I faced the same issue and I think this is due to the fact that the password is 'str' instead of 'bytes' as expected.
You can solve it by encoding the password while passing it to hashlib.pbkdf2_hmac()
so
```python
    hashed = hashlib.pbkdf2_hmac('sha256', password, salt, rounds)
```
becomes
```python
hashed = hashlib.pbkdf2_hmac('sha256', password.encode(), salt, rounds)
```

> 'utf-8' being the default encoding.

**Comment by gsunil99** [comment]
@brewsfab Thanks..

**Comment by a4v2d4** [comment]
If you're here in 2024 (or 2025?), there are two changes you need to make:

1. You need to update that line @brewsfab mentioned in `users.py` (line 37):
```python
hashed = hashlib.pbkdf2_hmac('sha256', password, salt, rounds)
```
becomes
```python
hashed = hashlib.pbkdf2_hmac('sha256', password.encode(), salt, rounds)
```

2. But you also need to fix `auth.py` line 12:

```python
    actual = hashlib.pbkdf2_hmac(
        record['hash'],
        password,
        record['salt'].value,
        record['rounds']
    )
```
becomes this
```python
    actual = hashlib.pbkdf2_hmac(
        record['hash'],
        password.encode(),
        record['salt'].value,
        record['rounds']
    )
```
